environment: dev

# Development overrides
vote:
  replicaCount: 1
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

result:
  replicaCount: 1
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

worker:
  replicaCount: 1
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

postgres:
  storageClass: "standard" # standard is default in kind
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

redis:
  resources:
    requests:
      cpu: "20m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "64Mi"
