{{- if .Values.vote.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vote
  labels:
    app: vote
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vote
  minReplicas: {{ .Values.vote.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.vote.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.vote.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
